[YASTM]
allowPartiallyFillingSoulGemsGlobal = [0xd92, "YASTM.esp"]
allowSoulDisplacementGlobal = [0xd8e, "YASTM.esp"]
allowSoulRelocationGlobal = [0xd8f, "YASTM.esp"]
allowSoulShrinkingGlobal = [0xd90, "YASTM.esp"]
allowSoulSplittingGlobal = [0xdc2, "YASTM.esp"]
allowExtraSoulRelocationGlobal = [0xdc1, "YASTM.esp"]
# Only used when soul diversion support is turned on.
allowSoulDiversionGlobal = [0xd91, "YASTM.esp"]
preserveOwnershipGlobal = [0xdc0, "YASTM.esp"]
allowNotificationsGlobal = [0xd93, "YASTM.esp"]
allowProfilingGlobal = [0xdc3, "YASTM.esp"]
