# This configuration is only read when using a DLL that's compiled with
# YASTM_SOULDIVERSION_ENABLED
#
# Note: You only need one of the two to exclude Inigo from the Soul Diversion
#       system.
#
#       The only difference is that the reference version will only apply to the
#       Inigo that's spawned with the mod.
#
#       The other will apply to any Inigo created with 'placeatme' console
#       command.
#
#       Any forms that aren't loaded once the main menu loads will not be
#       considered, so there's a distinct possibility that non-persistent
#       reference forms won't work.
#
#       If you need to pick which list to add to, prefer the base form unless
#       using the reference form really makes more sense.
[YASTM.diversion]
actorBaseIgnores = [
    [0xd62, "Inigo.esp"] # Inigo (base)
]
actorRefIgnores = [
    [0x8ae9, "Inigo.esp"] # Inigo (reference)
]
